steps:
#  - name: gradle:7.4.2-jdk11
#    entrypoint: gradle
#    args: ['--version']
#  - name: gradle:7.4.2-jdk11
#    entrypoint: gradle
#    args: [ "test" ]
  - name: gradle:7.4.2-jdk11
    entrypoint: gradle
    args: [ "assemble" ]
  - name: gcr.io/cloud-builders/docker
    args: [
      "build",
      "-t",
      "gcr.io/$PROJECT_ID/product-backend-api:$COMMIT_SHA",
      "--build-arg=JAR_FILE=build/libs/backend-restful-api-0.0.1-SNAPSHOT.jar",
      "."
    ]