apiVersion: v1
kind: Service
metadata:
  name: product-db-service
spec:
  selector:
    app: product-db
  ports:
  - port: 3344
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-db-deployment
spec:
  selector:
    matchLabels:
      app: product-db
  template:
    metadata:
      labels:
        app: product-db
    spec:
      containers:
      - name: product-db
        image: postgres:10
        resources:
          limits:
            cpu: "900m"
          requests:
            cpu: "100m"
        ports:
        - containerPort: 3344
