apiVersion: v1
kind: Secret
metadata:
  name: product-secret
type: Opaque
data:
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres
  POSTGRES_DB: C22_PS167_DB
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres
  DATABASE_URL: jdbc:postgresql://localhost:5432/C22_PS167_DB
  API_KEY_HEADER: X-API-KEY
  API_KEY: secret
