apiVersion: v1
kind: Service
metadata:
  name: product-db-service
spec:
  selector:
    app: product-db
  ports:
  - port: 3344
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-db-deployment
spec:
  selector:
    matchLabels:
      app: product-db
  template:
    metadata:
      labels:
        app: product-db
    spec:
      containers:
      - name: product-db
        image: postgres:10
        resources:
          limits:
            cpu: "900m"
          requests:
            cpu: "100m"
        ports:
        - containerPort: 3344
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: product-db-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: product-db-secret
                key: POSTGRES_USER
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: product-db-secret
                key: POSTGRES_DB
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: <volume>
      volumes:
        - name: <volume>
          persistentVolumeClaim:
            claimName: product-pvc
