apiVersion: v1
kind: Secret
metadata:
  name: product-secret
stringData:
  JDBC_DATABASE_USERNAME: <DATABASE_USERNAME>
  JDBC_DATABASE_PASSWORD: <DATABASE_PASSWORD>
  JDBC_DATABASE_URL: jdbc:postgresql://<HOST>:<PORT>/<DATABASE_NAME>
  API_KEY_HEADER: <HEADER_NAME>
  API_KEY: <HEADER_VALUE>
